#!/usr/bin/env python3
"""Prove the square-footprint views are square, not full-width.

hyprland tiles this app to about 621x670 - very nearly square itself - so a view
that keeps a square footprint looks identical to one that fills the width when
it is measured inside the app's own window. This runs the view alone inside a
deliberately WIDE parent (980x560) and draws the parent's bounds behind it, so
the capture shows whether the view is indented to a square or spanning edge to
edge.

    python3 scripts/probe-square.py
"""
import os
import subprocess
import sys
import time

APP = os.path.expanduser("~/exochronometer-linux/build/app")
TITLE = "square-probe"
PARENT_W, PARENT_H = 980, 560

TEMPLATE = '''import QtQuick
import QtQuick.Window
import "core/exoSnapshot.mjs" as Exo

// Generated by scripts/probe-square.py - not part of the app.
Window {{
    width: 621
    height: 670
    visible: true
    color: "#0d0d11"
    title: "{title}"

    readonly property var snap: Exo.capture(new Date())

    // A deliberately WIDE parent: the view is free to fill it, so anything
    // narrower than {pw}px is the view choosing a square footprint.
    Item {{
        id: wide
        x: 0
        y: 40
        width: {pw}
        height: {ph}

        Rectangle {{
            anchors.fill: parent
            color: "#2a2a3a"
            border.color: "#ff8800"
            border.width: 2
        }}

        {view} {{
            anchors.fill: parent
            live: true
            snapshot: wide.parent.snap
            fundamentalsOff: true
        }}
    }}
}}
'''


def window_geometry():
    import json
    out = subprocess.run(["hyprctl", "clients", "-j"], capture_output=True, text=True).stdout
    try:
        for c in json.loads(out):
            if c.get("title") == TITLE:
                x, y = c["at"]
                w, h = c["size"]
                return x, y, w, h
    except ValueError:
        pass
    return None


def main():
    view = sys.argv[1] if len(sys.argv) > 1 else "ColorMappingView"
    path = os.path.join(APP, "square-probe.qml")
    open(path, "w").write(TEMPLATE.format(title=TITLE, pw=PARENT_W, ph=PARENT_H, view=view))
    proc = subprocess.Popen(["qml6", "square-probe.qml"], cwd=APP,
                            stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    time.sleep(5)
    # The window's position is hyprland's business, not ours - hardcoding a
    # region captures whatever else happens to be there.
    geo = window_geometry()
    out = f"/tmp/square-{view}.png"
    if not geo:
        print(f"{view}: FAIL  no window titled {TITLE}")
        proc.terminate()
        return 1
    x, y, w, h = geo
    subprocess.run(["grim", "-g", f"{x},{y} {w}x{h}", out], capture_output=True)
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
    size = os.path.getsize(out) if os.path.exists(out) else 0
    print(f"{view}: {'ok' if size else 'FAIL'}  {size} bytes -> {out}")
    return 0 if size else 1


if __name__ == "__main__":
    sys.exit(main())