#!/usr/bin/env python3
"""Render AppShell in specific states to PNGs.

Replaces render-modes.py, which worked by editing main.qml. After the two-host
refactor the page state lives in AppShell.qml, so this instantiates AppShell in
a throwaway window and drives it through objectName lookups rather than text
surgery - no source rewriting that can silently fail to apply.

Why grabToImage: the desktop may be locked, and grim would then capture the lock
overlay. grabToImage renders the item tree offscreen, so it works regardless.

Everything the harness wants to REPORT has to end up on screen, because
console.log is silent in this Qt build. The audio render cost is read back off
the rendered image (see the AUDIO status line in HarmonicSpectrumPage).

    python3 scripts/shoot-states.py [name ...]
"""
import os
import subprocess
import sys

APP = os.path.expanduser("~/exochronometer-linux/build/app")

# name, shell.page, setup JS, grab delay ms
STATES = [
    ("circles",          0, "", 2600),
    ("misc-phase",       2, 'setMode("exoMisc", 0)', 3200),
    ("misc-cents",       2, 'setMode("exoMisc", 1)', 3200),
    ("misc-color",       2, 'setMode("exoMisc", 6)', 3200),
    ("misc-selector",    2, 'setMode("exoMisc", 8)', 3800),
    ("misc-geometry",    2, 'setMode("exoMisc", 9)', 3800),
    ("spectrum",         4, "", 3200),
    ("spectrum-diag",    4, 'report()', 3000),
    ("spectrum-synth",   4, 'set("exoSpectrum", "showSynth", true)', 3200),
    ("spectrum-audio",   4, 'set("exoSpectrum", "showSynth", true); '
                            'call("exoSpectrum", "toggleAudio")', 14000),
    # Reports WHICH player the page loaded, not just that something is playing.
    ("spectrum-rt",      4, 'call("exoSpectrum", "toggleAudio"); later(12000, reportAudio)', 16000),
]

TEMPLATE = '''import QtQuick
import QtQuick.Window

// Generated by scripts/shoot-states.py - not part of the app.
Window {{
    width: 1180
    height: 940
    visible: true
    color: "#0d0d11"
    title: "Exochronometer state: {name}"

    // The green strip along the bottom. It was being ASSIGNED without ever being
    // declared, so every "diag" state has been showing nothing at all.
    property string diag: ""

    // A FIXED-SIZE item tree, grabbed directly. hyprland tiles this app to about
    // 621x670, so a window-sized grab would hide every change that depends on
    // being wider than it is tall (the square colour field, the square selector
    // grid, the side-by-side spectrum/synth split). grabToImage renders the item
    // at ITS size, offscreen, so the window's real size does not matter.
    Item {{
        id: canvas
        width: 1020
        height: 760

        AppShell {{
            id: shell
            anchors.fill: parent
            allowQuit: false
            page: {page}
        }}

        Rectangle {{
            x: 0
            y: 700
            width: canvas.width
            height: 44
            color: "#000000"
            Text {{
                x: 8
                y: 8
                text: diag
                color: "#00ff00"
                font.family: "monospace"
                font.pixelSize: 12
            }}
        }}
    }}

    function byName(item, name) {{
        if (!item) return null
        if (item.objectName === name) return item
        const kids = item.children
        for (let i = 0; i < kids.length; i++) {{
            const hit = byName(kids[i], name)
            if (hit) return hit
        }}
        return null
    }}

    function setMode(name, m) {{
        const target = byName(shell, name)
        if (target) target.mode = m
    }}

    function set(name, prop, value) {{
        const target = byName(shell, name)
        if (target) target[prop] = value
    }}

    function call(name, fn) {{
        const target = byName(shell, name)
        if (target && typeof target[fn] === "function") target[fn]()
    }}

    // Run something after a delay, without touching the template's own timers.
    function later(ms, fn) {{
        const t = Qt.createQmlObject(
            "import QtQuick; Timer {{ interval: " + ms + "; running: true; repeat: false }}",
            canvas)
        t.triggered.connect(fn)
    }}

    // Which audio player the SPECTRUM page actually loaded, and is it the
    // real-time one? This is the wiring the suite cannot see from the outside:
    // the page prefers RealtimePlayer.qml and falls back to SynthPlayer.qml.
    function reportAudio() {{
        const s = byName(shell, "exoSpectrum")
        if (!s) {{ diag = "AUDIO no spectrum page"; return }}
        const ldr = byName(s, "audioLoader")
        if (!ldr) {{ diag = "AUDIO no audioLoader"; return }}
        const it = ldr.item
        if (!it) {{ diag = "AUDIO loader item NULL (loader " + ldr.status + ")"; return }}
        const t = byName(s, "audioStatus")
        // Compare against the PARENT. An un constrained Text sets its own width to
        // its painted width, so `paintedWidth > width` can never fire - a check
        // that cannot fail. What matters is whether it overflows its container.
        const avail = t && t.parent ? Math.round(t.parent.width) : 0
        const fit = t
            ? ("painted=" + Math.round(t.paintedWidth) + " avail=" + avail
               + (t.paintedWidth > avail + 0.5 ? " OVERFLOW" : " fits"))
            : "no audioStatus text"
        // The fit numbers go FIRST: the strip is 1020 px wide and long diag text
        // gets clipped, which is exactly how a measurement goes missing.
        diag = fit + " | rt=" + (("bankProvider" in it) ? "yes" : "no")
             + " | " + it.detail.replace(/\u00B7/g, "|")
    }}

    // What the spectrum page actually sees when its canvas comes up blank.
    function report() {{
        const s = byName(shell, "exoSpectrum")
        if (!s) {{ diag = "NO SPECTRUM PAGE"; return }}
        const snap = s.snapshot
        diag = "snap=" + (snap ? "yes" : "NULL")
             + " live=" + s.live
             + " page=" + shell.page
             + " w=" + Math.round(s.width) + " h=" + Math.round(s.height)
    }}

    Timer {{
        interval: 2500
        running: true
        repeat: false
        onTriggered: {{ {setup} }}
    }}

    Timer {{
        interval: {delay}
        running: true
        repeat: false
        onTriggered: {{
            canvas.grabToImage(function (r) {{
                Qt.exit(r.saveToFile("file:///tmp/state-{name}.png") ? 0 : 3)
            }})
        }}
    }}
}}
'''


def main():
    wanted = sys.argv[1:]
    states = [s for s in STATES if not wanted or s[0] in wanted]
    if not states:
        print("no matching state; known:", ", ".join(s[0] for s in STATES))
        return 1

    path = os.path.join(APP, "state-grab.qml")
    ok = True
    for name, page, setup, delay in states:
        open(path, "w").write(TEMPLATE.format(name=name, page=page, setup=setup, delay=delay))
        out = "/tmp/state-%s.png" % name
        if os.path.exists(out):
            os.remove(out)
        try:
            import os as _o
            env = dict(_o.environ)
            env["QML_IMPORT_PATH"] = str(os.path.join(os.path.dirname(APP), "audio"))
            rc = subprocess.run(["qml6", "state-grab.qml"], cwd=APP, timeout=40, env=env,
                                stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
            rc, err = rc.returncode, rc.stderr.decode()[:200]
        except subprocess.TimeoutExpired:
            rc, err = -1, "timeout"
        size = os.path.getsize(out) if os.path.exists(out) else 0
        if size:
            print("%-16s ok    %7d bytes  %s" % (name, size, out))
        else:
            ok = False
            print("%-16s FAIL  exit=%s  %s" % (name, rc, err.strip()[:120]))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())